name: Create a production build to gh-sources
on:
  push:
    branches: [main]
env:
  TZ: Asia/Dhaka


jobs:
  BuildandPush:
    concurrency: gh-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: "yarn"

      - name: Adapt for GitHub Pages
        run: |
          git config --global user.name 'shahnewaz171' 
          git config --global user.email 'shahnewaz601@gmail.com' 
          git fetch
          ghPagesChanges=$(git log origin/gh-sources -n 1 --pretty=format:"%H")
          git cherry-pick -s $ghPagesChanges
          git branch -m main gh-sources
          git push origin gh-sources -f
      - name: Install NPM packages
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
          git-config-name: shahnewaz171
          git-config-email: shahnewaz601@gmail.com
          commit-message: "Deployed production build 🚀"
          single-commit: true
          silent: true
